[package]
name = "rust-cli-csv-processor"
version = "0.1.0"
authors = ["MerlinQWQ <MerlinSMQWQ@proton.me>"]
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
csv = "1.4.0"
serde = { version = "1.0.228", features = ["derive"] }
